### ISSUE TITLE
failing to build css on specific image url

### ISSUE THREAD

**Issue by lancejpollard** [duojs/pack#18]
When a CSS file has this in it:

``` css
.SelectField-caret {
  background: url("images/caret-grey.svg") no-repeat center #FCFAF5;
  height: 30px;
  width: 30px;
  position: absolute;
  bottom: 11px;
  right: 10px;
  display: block;
  pointer-events: none;
}
```

It errors out like this:

```
error : Error: { [Error: Command failed: /bin/sh -c git ls-remote --tags --heads https://<token>@github.com/images/caret-grey.svg
remote: Repository not found.
fatal: repository 'https://<token>@github.com/images/caret-grey.svg/' not found
]
  killed: false,
  code: 128,
  signal: null,
  cmd: '/bin/sh -c git ls-remote --tags --heads https://<token>@github.com/images/caret-grey.svg' }
    at error (/Users/lancejpollard/dev/segmentio/app/node_modules/duo/node_modules/duo-package/node_modules/gh-resolve/index.js:167:10)
    at /Users/lancejpollard/dev/segmentio/app/node_modules/duo/node_modules/duo-package/node_modules/gh-resolve/index.js:68:37
    at ChildProcess.exithandler (child_process.js:736:5)
    at ChildProcess.EventEmitter.emit (events.js:110:17)
    at maybeClose (child_process.js:992:16)
    at Socket.<anonymous> (child_process.js:1142:11)
    at Socket.EventEmitter.emit (events.js:107:17)
    at Pipe.close (net.js:461:12)
```

If you just add a `./` at the start of the URL, it works:

``` css
.SelectField-caret {
  background: url("./images/caret-grey.svg") no-repeat center #FCFAF5;
  height: 30px;
  width: 30px;
  position: absolute;
  bottom: 11px;
  right: 10px;
  display: block;
  pointer-events: none;
}
```

Should both cases be supported or no? It worked both ways on component.

Also sidenote (will create another issue for it). The logs print out the token it looks like, so if people copy/paste their errors, others could easily steal that token and use the GitHub API as another person, so that should probably be hidden somehow. I just replaced it with `<token>` above.
